<?php

return [
    'enabled' => [
        'value' => true,
        'xtype' => 'combo-boolean',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_enabled',
        'description' => 'setting_imageoptimizer_enabled_desc',
    ],
    'formats' => [
        'value' => 'webp',
        'xtype' => 'textfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_formats',
        'description' => 'setting_imageoptimizer_formats_desc',
    ],
    'avif_enabled' => [
        'value' => false,
        'xtype' => 'combo-boolean',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_avif_enabled',
        'description' => 'setting_imageoptimizer_avif_enabled_desc',
    ],
    'quality' => [
        'value' => 82,
        'xtype' => 'numberfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_quality',
        'description' => 'setting_imageoptimizer_quality_desc',
    ],
    'quality_jpeg' => [
        'value' => 82,
        'xtype' => 'numberfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_quality_jpeg',
        'description' => 'setting_imageoptimizer_quality_jpeg_desc',
    ],
    'quality_png' => [
        'value' => 90,
        'xtype' => 'numberfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_quality_png',
        'description' => 'setting_imageoptimizer_quality_png_desc',
    ],
    'breakpoints' => [
        'value' => '480,768,1024,1440,1920',
        'xtype' => 'textfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_breakpoints',
        'description' => 'setting_imageoptimizer_breakpoints_desc',
    ],
    'variant_pattern' => [
        'value' => '{basename}.{width}.{ext}',
        'xtype' => 'textfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_variant_pattern',
        'description' => 'setting_imageoptimizer_variant_pattern_desc',
    ],
    'upscale' => [
        'value' => false,
        'xtype' => 'combo-boolean',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_upscale',
        'description' => 'setting_imageoptimizer_upscale_desc',
    ],
    'responsive_min_width' => [
        'value' => 320,
        'xtype' => 'numberfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_responsive_min_width',
        'description' => 'setting_imageoptimizer_responsive_min_width_desc',
    ],
    'default_sizes' => [
        'value' => '(min-width: 1280px) 50vw, 100vw',
        'xtype' => 'textarea',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_default_sizes',
        'description' => 'setting_imageoptimizer_default_sizes_desc',
    ],
    'inject_frontend' => [
        'value' => true,
        'xtype' => 'combo-boolean',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_inject_frontend',
        'description' => 'setting_imageoptimizer_inject_frontend_desc',
    ],
    'inject_email' => [
        'value' => false,
        'xtype' => 'combo-boolean',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_inject_email',
        'description' => 'setting_imageoptimizer_inject_email_desc',
    ],
    'skip_classes' => [
        'value' => 'lazy,swiper-lazy,no-optim',
        'xtype' => 'textfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_skip_classes',
        'description' => 'setting_imageoptimizer_skip_classes_desc',
    ],
    'skip_src_pattern' => [
        'value' => 'thumb3x',
        'xtype' => 'textfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_skip_src_pattern',
        'description' => 'setting_imageoptimizer_skip_src_pattern_desc',
    ],
    'respect_existing_srcset' => [
        'value' => true,
        'xtype' => 'combo-boolean',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_respect_existing_srcset',
        'description' => 'setting_imageoptimizer_respect_existing_srcset_desc',
    ],
    'respect_existing_picture' => [
        'value' => true,
        'xtype' => 'combo-boolean',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_respect_existing_picture',
        'description' => 'setting_imageoptimizer_respect_existing_picture_desc',
    ],
    'respect_existing_loading' => [
        'value' => true,
        'xtype' => 'combo-boolean',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_respect_existing_loading',
        'description' => 'setting_imageoptimizer_respect_existing_loading_desc',
    ],
    'method_priority' => [
        'value' => 'cwebp,gd,imagick',
        'xtype' => 'textfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_method_priority',
        'description' => 'setting_imageoptimizer_method_priority_desc',
    ],
    'cron_limit' => [
        'value' => 200,
        'xtype' => 'numberfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_cron_limit',
        'description' => 'setting_imageoptimizer_cron_limit_desc',
    ],
    'html_cache' => [
        'value' => true,
        'xtype' => 'combo-boolean',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_html_cache',
        'description' => 'setting_imageoptimizer_html_cache_desc',
    ],
    'convert_on_upload' => [
        'value' => true,
        'xtype' => 'combo-boolean',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_convert_on_upload',
        'description' => 'setting_imageoptimizer_convert_on_upload_desc',
    ],
    'convert_on_upload_sync_timeout' => [
        'value' => 5,
        'xtype' => 'numberfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_convert_on_upload_sync_timeout',
        'description' => 'setting_imageoptimizer_convert_on_upload_sync_timeout_desc',
    ],
    'reencode_if_unchanged' => [
        'value' => false,
        'xtype' => 'combo-boolean',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_reencode_if_unchanged',
        'description' => 'setting_imageoptimizer_reencode_if_unchanged_desc',
    ],
    'preserve_exif' => [
        'value' => false,
        'xtype' => 'combo-boolean',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_preserve_exif',
        'description' => 'setting_imageoptimizer_preserve_exif_desc',
    ],
    'preserve_icc' => [
        'value' => true,
        'xtype' => 'combo-boolean',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_preserve_icc',
        'description' => 'setting_imageoptimizer_preserve_icc_desc',
    ],
    'max_memory_limit' => [
        'value' => '512M',
        'xtype' => 'textfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_max_memory_limit',
        'description' => 'setting_imageoptimizer_max_memory_limit_desc',
    ],
    'stuck_minutes' => [
        'value' => 30,
        'xtype' => 'numberfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_stuck_minutes',
        'description' => 'setting_imageoptimizer_stuck_minutes_desc',
    ],
    'retention_days' => [
        'value' => 30,
        'xtype' => 'numberfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_retention_days',
        'description' => 'setting_imageoptimizer_retention_days_desc',
    ],
    'max_html_size' => [
        'value' => 1048576,
        'xtype' => 'numberfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_max_html_size',
        'description' => 'setting_imageoptimizer_max_html_size_desc',
    ],
    'skip_lazy_first_images' => [
        'value' => 0,
        'xtype' => 'numberfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_skip_lazy_first_images',
        'description' => 'setting_imageoptimizer_skip_lazy_first_images_desc',
    ],
    'cleanup_on_uninstall' => [
        'value' => false,
        'xtype' => 'combo-boolean',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_cleanup_on_uninstall',
        'description' => 'setting_imageoptimizer_cleanup_on_uninstall_desc',
    ],
    'disk_warn_gb' => [
        'value' => 10,
        'xtype' => 'numberfield',
        'area' => 'imageoptimizer',
        'name' => 'setting_imageoptimizer_disk_warn_gb',
        'description' => 'setting_imageoptimizer_disk_warn_gb_desc',
    ],
];
